#version 460 core

layout (local_size_x = 8, local_size_y = 8) in;
layout (rgba8, binding = 0) uniform image2D screen;

void main() {
    ivec2 texCoord = ivec2(gl_GlobalInvocationID.xy);
    vec3 color = imageLoad(screen, texCoord).rgb;
    float brightness = dot(color, vec3(0.2126, 0.7152, 0.0722));
    
    // Apply a threshold to extract only bright areas
    // color = brightness > 1 ? color : vec3(0.0);
    imageStore(screen, texCoord, vec4(color, 1));
}